export const SET_LOADING = "loading/set"
export const UNSET_LOADING = "loading/unset"
export const SELECT_ITEM = "items/select"
export const DESELECT_ITEM = "items/unselect"
export const SET_AVAILABLE_ITEMS = "items/set"